install:
  - set PATH=C:\Ruby21-x64\bin;%PATH%
  - gem install bundler -v 1.14.6 -f
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
